In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname')

In [4]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [5]:
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,...,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [6]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Age,QID127,What is your age?*,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,True,MC,MAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
Check,QID341,Just checking to make sure you are paying atte...,True,MC,SAVR
...,...,...,...,...,...
JobSatPoints_7,QID337,"Learning and using new technology, including p...",NaN,MC,MAVR
JobSatPoints_8,QID337,"Designing and building environments, databases...",NaN,MC,MAVR
JobSatPoints_9,QID337,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
JobSatPoints_10,QID337,Working with new and/or top-quality hardware,NaN,MC,MAVR
JobSatPoints_11,QID337,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

In [7]:
df['CompTotal'].median()

np.float64(110000.0)

In [9]:
df.median(numeric_only=True)

CompTotal              110000.0
WorkExp                     9.0
JobSatPoints_1             10.0
JobSatPoints_4              0.0
JobSatPoints_5              0.0
JobSatPoints_6             20.0
JobSatPoints_7             15.0
JobSatPoints_8             10.0
JobSatPoints_9              5.0
JobSatPoints_10             0.0
JobSatPoints_11             0.0
ConvertedCompYearly     65000.0
JobSat                      7.0
dtype: float64

In [11]:
df.describe()

,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [12]:
df['CompTotal'].count()

np.int64(33740)

In [13]:
df['CodingActivities'].value_counts()

CodingActivities
Hobby                                                                                                                                                                              9993
I don’t code outside of work                                                                                                                                                       6508
Hobby;Professional development or self-paced learning from online courses                                                                                                          6203
Hobby;Contribute to open-source projects                                                                                                                                           3732
Professional development or self-paced learning from online courses                                                                                                                3120
                                                                                                                                                                                   ...
Hobby;Contribute to open-source projects;Other (please specify):;School or academic work;Freelance/contract work                                                                      1
Other (please specify):;Bootstrapping a business;School or academic work                                                                                                              1
Contribute to open-source projects;Other (please specify):;Bootstrapping a business;School or academic work;Professional development or self-paced learning from online courses       1
Hobby;Contribute to open-source projects;Other (please specify):;Bootstrapping a business;School or academic work                                                                     1
Hobby;Other (please specify):;Bootstrapping a business;School or academic work;Professional development or self-paced learning from online courses;Freelance/contract work            1
Name: count, Length: 118, dtype: int64

In [15]:
df['Employment']

ResponseId
1        Employed, full-time
2        Employed, full-time
3        Employed, full-time
4         Student, full-time
5         Student, full-time
                ...
65433    Employed, full-time
65434    Employed, full-time
65435    Employed, full-time
65436    Employed, full-time
65437     Student, full-time
Name: Employment, Length: 65437, dtype: object

In [21]:
schema_df.loc['DevType']

qid                                                       QID31
question      Which of the following describes your current ...
force_resp                                                False
type                                                         MC
selector                                                   SAVR
Name: DevType, dtype: object

In [22]:
df['DevType'].value_counts(normalize=True)

DevType
Developer, full-stack                            0.307175
Developer, back-end                              0.167012
Student                                          0.085827
Developer, front-end                             0.056338
Developer, desktop or enterprise applications    0.041938
Other (please specify):                          0.041349
Developer, mobile                                0.033998
Developer, embedded applications or devices      0.027303
Engineering manager                              0.021448
Academic researcher                              0.020826
Data engineer                                    0.018807
Data scientist or machine learning specialist    0.017226
DevOps specialist                                0.017142
Research & Development role                      0.015863
Senior Executive (C-Suite, VP, etc.)             0.014080
Developer, game or graphics                      0.011877
Cloud infrastructure engineer                    0.010665
System administrator                             0.009286
Developer, AI                                    0.009134
Developer, QA or test                            0.008832
Data or business analyst                         0.008798
Project manager                                  0.007032
Security professional                            0.005989
Educator                                         0.005972
Scientist                                        0.005585
Engineer, site reliability                       0.005215
Product manager                                  0.004878
Blockchain                                       0.003953
Developer Experience                             0.003768
Hardware Engineer                                0.003364
Designer                                         0.003062
Database administrator                           0.002877
Developer Advocate                               0.001766
Marketing or sales professional                  0.001615
Name: proportion, dtype: float64

In [26]:
df['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Micronesia, Federated States of...                          1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [27]:
country_grp = df.groupby(['Country'])

In [28]:
country_grp

In [40]:
country_grp.get_group('Philippines')

C:\Users\PC\AppData\Local\Temp\ipykernel_10968\3094930765.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('Philippines')

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,...,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
14,"I used to be a developer by profession, but no...",35-44 years old,"Not employed, and not looking for work",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Colleague;Other online resources (e.g., videos...",Technical documentation;Blogs;Stack Overflow;I...,API document(s) and/or SDK document(s);User gu...,20,NaN,Other (please specify):,NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,PHP;Python,Python,Python,MariaDB;MySQL,NaN,NaN,NaN,NaN,NaN,CodeIgniter,NaN,NaN,CMake,NaN,NaN,NaN,NaN,NaN,Ant;APT,NaN,NaN,...,NaN,NaN,NaN,NaN,I'm not sure,Biased results that do not represent diverse v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
30,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Colleague;Other online resources (e.g., videos...",Technical documentation;Blogs;Stack Overflow,API document(s) and/or SDK document(s);User gu...,9,6,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,C#;HTML/CSS;JavaScript;SQL,C#;HTML/CSS;JavaScript;Kotlin;SQL;TypeScript,C#;HTML/CSS;JavaScript;SQL,Microsoft SQL Server;MongoDB;SQLite,Cosmos DB;Dynamodb;Elasticsearch;Firebase Real...,Microsoft SQL Server;MongoDB;SQLite,Microsoft Azure,Amazon Web Services (AWS);Firebase;Microsoft A...,Microsoft Azure,AngularJS;ASP.NET;ASP.NET CORE;jQuery;Node.js;...,ASP.NET;ASP.NET CORE;Blazor;Express;Next.js;No...,ASP.NET;ASP.NET CORE;Node.js;React,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8),.NET (5+) ;.NET MAUI;Flutter,.NET (5+),NuGet;Visual Studio Solution,Docker;Kubernetes;npm;NuGet;Terraform;Visual S...,NuGet;Visual Studio Solution,...,Writing code,Search for answers,NaN,NaN,No,Circulating misinformation or disinformation;B...,Don’t trust the output or answers;Not everyone...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
174,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;On the job training;Other online res...,Stack Overflow;Social Media;How-to videos;AI;C...,NaN,5,Less than 1 year,"Developer, back-end",NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,HTML/CSS;JavaScript,Python;SQL;VBA,NaN,NaN,NaN,NaN,Google Cloud,Amazon Web Services (AWS);Microsoft Azure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,I'm not sure,Missing or incorrect attribution for sources o...,Don’t trust the output or answers;AI tools lac...,Yes,Individual contributor,1.0,Neither agree nor disagree,Disagree,Agree,Neither agree nor disagree,Agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Strongly disagree,Never,3-5 times a week,Never,15-30 minutes a day,15-30 minutes a day,Complexity of tech stack for deployment;Comple...,Knowledge sharing community;AI-assisted techno...,Cloud only (single or multi-cloud),Traditional public search engine,"Internet, Telecomm or Information Services",10.0,8.0,10.0,10.0,10.0,9.0,10.0,10.0,8.0,Too long,Neither easy nor difficult,NaN,5.0
419,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Apples,Hobby;Bootstrapping a business,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,22,17,Engineering manager,NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,Bash/Shell (all shells);Groovy;HTML/CSS;Java;J...,Bash/Shell (all shells);Groovy;HTML/CSS;Java;J...,Bash/Shell (all shells);Groovy;HTML/CSS;Java;J...,Firebase Realtime Database;H2;Microsoft Access...,Firebase Realtime Database;H2;Microsoft Access...,Firebase Realtime Database;H2;Microsoft Access...,Amazon Web Services (AWS);Cloudflare;Colocatio...,Amazon Web Services (AWS);Cloudflare;Colocatio...,Amazon Web Services (AWS);Cloudflare;Colocatio...,Angular;AngularJS;Express;jQuery;Node.js;React...,Angular;AngularJS;Express;jQuery;Node.js;React...,Angular;AngularJS;Express;jQuery;Node.js;React...,NaN,NaN,NaN,.NET (5+) ;Capacitor;Electron;Ionic;NumPy;Spri...,.NET (5+) ;Capacitor;Electron;Ionic;NumPy;Spri...,.NET (5+) ;Capacitor;Electron;Ionic;NumPy;Spri...,Ant;APT;Chef;Chocolatey;Composer;Docker;Gradle...,Ant;APT;Chef;Chocolatey;Composer;Docker;Gradle...,Ant;APT;Chef;Chocolatey;Composer;Docker;Gradle...,...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;AI tools lac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
1023,I am a developer by profession,25-34 years old,"Not employed, but looking for work;Not employe...",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,13,3,Other (please specify):,NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,C#;C++;HTML/CSS;JavaScript;Python;Rust,C#;C++;Python;Rust,C#;C++;Python;Rust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;GNU GCC;LLVM's Clang;MSVC,NaN,NaN,.NET (5+) ;TensorFlow,.NET (5+) ;OpenGL,.NET (5+),APT;Visual Studio Solution,APT,APT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60421,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Technical documentation;Stack Overflow;Coding ...,API document(s) and/or SDK document(s);User gu...,13,9,"Developer, full-stack",500 to 999 employees,I have some influence,Start a free trial;Visit developer communities...,Out-of-the-box is ready to go with little need...,APIs;Integrated developer community;Quality su...,Philippines,PHP\tPhilippine peso,NaN,Go;HTML/CSS;Java;JavaScript;PHP;Python;SQL;Typ...,NaN,NaN,Elasticsearch;MariaDB;Microsoft SQL Server;Mon...,NaN,NaN,Amazon Web Services (AWS);Digital Ocean;OpenSt...,NaN,NaN,Angular;AngularJS;jQuery;Laravel;Node.js;React...,NaN,NaN,NaN,NaN,NaN,Spring Framework,NaN,NaN,Homebrew;Kubernetes;Maven (build tool);npm,NaN,NaN,...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;R...,Not everyone uses them,Yes,Individual contributor,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60751,I am a developer by profession,25-34 years old,"Not employed, but looking for work",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;On the job training;Other online res...,Technical documentation;Written Tutorials;Stac...,API document(s) and/or SDK document(s);AI-powe...,9,5,Other (please specify):,NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,HTML/CSS;JavaScript;PHP;SQL,HTML/CSS;JavaScript;PHP;SQL,HTML/CSS;JavaScript;PHP;SQL,MariaDB;MySQL;Redis,MariaDB;MySQL;Redis,MariaDB;MySQL;Redis,NaN,NaN,NaN,Vue.js,Node.js;React;Vue.js,Vue.js,NaN,NaN,NaN,NaN,NaN,NaN,Composer;Kubernetes,Composer;Kubernetes,Composer;Kubernetes,...,NaN,Writing code;Debugging and getting help;Commit...,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;M...,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
61783,I code primarily as a hobby,Under 18 years old,"Student, part-time",NaN,Apples,NaN,Some college/university study without earning ...,Other (please specify):,NaN,NaN,3,NaN,Student,NaN,NaN,NaN,NaN,NaN,Philippines,NaN,NaN,NaN,NaN,NaN,MySQL,NaN,NaN,NaN,NaN,NaN,Flask,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Testing code;Committing and reviewing code;Dep...,NaN,NaN,Yes,Missing or incorrect attribution for sources o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63142,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Written Tutorials;Stack Overflow;Social Media;...,NaN,25,18,"Developer, mobile",2 to 9 employees,I have some influence,Ask developers I know/work with;Read ratings o...,Is ready-to-go but also customizable for growt...,APIs;Integrated developer community;Reputation...,Philippines,PHP\tPhilippine peso,NaN,Kotlin,HTML/CSS;JavaScript;Kotlin;Objective-C,Kotlin,Cloud Firestore;SQLite;Supabase,Cloud Firestore;Firebase Realtime Database,Cloud Firestore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers;Lack of prop...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63277,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Bootstrapping a business,Some college/university study without earning ...,On the job training;Other online resources (e....,Blogs;Written Tutorials;Stack Overflow;Coding ...,NaN,6,6,"Developer, full-stack",2 to 9 employees,I have some influence,Start a free trial,Is ready-to-go but also customizable for growt...,APIs;Customization;Integrated developer commun...,Philippines,PHP\tPhilippine peso,110000.0,HTML/CSS;JavaScript;SQL;TypeScript,HTML/CSS;JavaScript;SQL;TypeScript,HTML/CSS;JavaScript;SQL;TypeScript,Dynamodb;MongoDB;MySQL;Supabase,Dynamodb;MongoDB;MySQL;Supabase,Dynamodb;MongoDB;MySQL;Supabase,Amazon Web Services (AWS);Cloudflare;Netlify;V...,Amazon Web Services (AWS);Cloudflare;Netlify;V...,Amazon Web Services (AWS);Cloudflare;Netlify;V...,CodeIgniter;Deno;Express;Fastify;Next.js;Node....,Deno;Express;Fastify;Next.js;Node.js;React,Deno;Express;Fastify;Next.js;Node.js;React,NaN,NaN,NaN,React Native;SwiftUI,React Native,React Native,Docker;Homebrew;npm;pnpm;Pulumi;Vite;Webpack;Yarn,Docker;Homebrew;npm;pnpm;Pulumi;Vite;Webpack;Yarn,Docker;Homebrew;npm;pnpm;Pulumi;Vite;Webpack;Yarn,...,NaN,NaN,NaN,NaN,No,Biased results that do not represent diverse v...,We don’t have the right policies in place to r...,Yes,Individual contributor,6.0,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Amount of technical debt;Number of software to...,Microservices,Cloud only (single or multi-cloud),Traditional public search engine,Fintech,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Too long,Difficult,NaN,8.0

In [41]:
filt = df['Country'] == 'Philippines'
df.loc[filt]['DevType'].value_counts()

DevType
Developer, full-stack                            79
Student                                          23
Developer, back-end                              19
Developer, front-end                             16
Other (please specify):                          13
Developer, mobile                                 8
Cloud infrastructure engineer                     4
Developer, desktop or enterprise applications     4
Data or business analyst                          3
Academic researcher                               3
DevOps specialist                                 3
System administrator                              2
Engineering manager                               2
Developer, game or graphics                       2
Database administrator                            2
Engineer, site reliability                        2
Developer, AI                                     2
Product manager                                   1
Developer, QA or test                             1
Data scientist or machine learning specialist     1
Scientist                                         1
Project manager                                   1
Security professional                             1
Research & Development role                       1
Senior Executive (C-Suite, VP, etc.)              1
Name: count, dtype: int64

In [42]:
country_grp['DevType'].value_counts().head(50)

Country      DevType
Afghanistan  Developer, full-stack                            11
             Student                                           6
             Academic researcher                               4
             Data engineer                                     3
             Developer, back-end                               3
             Blockchain                                        2
             Data scientist or machine learning specialist     2
             Developer, embedded applications or devices       2
             Developer, mobile                                 2
             Other (please specify):                           2
             Security professional                             2
             Cloud infrastructure engineer                     1
             Database administrator                            1
             DevOps specialist                                 1
             Developer, desktop or enterprise applications     1
             Developer, front-end                              1
             Educator                                          1
             Engineering manager                               1
             Product manager                                   1
             Scientist                                         1
             System administrator                              1
Albania      Developer, full-stack                            16
             Developer, back-end                              10
             Student                                           5
             Security professional                             3
             Academic researcher                               2
             DevOps specialist                                 2
             Developer, front-end                              2
             Senior Executive (C-Suite, VP, etc.)              2
             Cloud infrastructure engineer                     1
             Designer                                          1
             Developer, AI                                     1
             Developer, QA or test                             1
             Developer, desktop or enterprise applications     1
Algeria      Developer, full-stack                            29
             Developer, front-end                              9
             Student                                           9
             Developer, back-end                               5
             Developer, mobile                                 4
             Developer, desktop or enterprise applications     3
             Data or business analyst                          2
             Educator                                          2
             Other (please specify):                           2
             Academic researcher                               1
             Data scientist or machine learning specialist     1
             Designer                                          1
             Developer, QA or test                             1
             Project manager                                   1
             Security professional                             1
             Senior Executive (C-Suite, VP, etc.)              1
Name: count, dtype: int64

In [43]:
country_grp['DevType'].value_counts().loc['Philippines']

DevType
Developer, full-stack                            79
Student                                          23
Developer, back-end                              19
Developer, front-end                             16
Other (please specify):                          13
Developer, mobile                                 8
Cloud infrastructure engineer                     4
Developer, desktop or enterprise applications     4
Academic researcher                               3
Data or business analyst                          3
DevOps specialist                                 3
Database administrator                            2
Developer, AI                                     2
Developer, game or graphics                       2
Engineer, site reliability                        2
Engineering manager                               2
System administrator                              2
Data scientist or machine learning specialist     1
Developer, QA or test                             1
Product manager                                   1
Project manager                                   1
Research & Development role                       1
Scientist                                         1
Security professional                             1
Senior Executive (C-Suite, VP, etc.)              1
Name: count, dtype: int64

In [44]:
country_grp['DevType'].value_counts(normalize=True).loc['Philippines']

DevType
Developer, full-stack                            0.405128
Student                                          0.117949
Developer, back-end                              0.097436
Developer, front-end                             0.082051
Other (please specify):                          0.066667
Developer, mobile                                0.041026
Cloud infrastructure engineer                    0.020513
Developer, desktop or enterprise applications    0.020513
Academic researcher                              0.015385
Data or business analyst                         0.015385
DevOps specialist                                0.015385
Database administrator                           0.010256
Developer, AI                                    0.010256
Developer, game or graphics                      0.010256
Engineer, site reliability                       0.010256
Engineering manager                              0.010256
System administrator                             0.010256
Data scientist or machine learning specialist    0.005128
Developer, QA or test                            0.005128
Product manager                                  0.005128
Project manager                                  0.005128
Research & Development role                      0.005128
Scientist                                        0.005128
Security professional                            0.005128
Senior Executive (C-Suite, VP, etc.)             0.005128
Name: proportion, dtype: float64

In [46]:
country_grp['CompTotal'].median().loc['Philippines']

np.float64(720000.0)

In [48]:
country_grp['CompTotal'].agg(['median', 'mean']).loc['Canada']

median    120000.000000
mean      177999.189548
Name: Canada, dtype: float64

In [53]:
filt = df['Country'] == 'Philippines'
df.loc[filt]['LanguageHaveWorkedWith'].str.contains('Python').sum()

83

In [54]:
country_grp['LanguageHaveWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [55]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [56]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [58]:
country_respondent = df['Country'].value_counts()
country_respondent

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Micronesia, Federated States of...                          1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [59]:
country_uses_python = country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [60]:
python_df = pd.concat([country_respondent, country_uses_python], axis='columns', sort=False)

In [61]:
python_df

,count,LanguageHaveWorkedWith
Country,,
United States of America,11095,6251
Germany,4947,2647
India,4231,2128
United Kingdom of Great Britain and Northern Ireland,3224,1638
Ukraine,2672,963
...,...,...
"Micronesia, Federated States of...",1,0
Nauru,1,0
Chad,1,1
Djibouti,1,0
Solomon Islands,1,0

In [65]:
python_df.rename(columns={'count':'NumRespondents', 'LanguageHaveWorkedWith':'NumKnowsPython'}, inplace=True)

In [66]:
python_df

,NumRespondents,NumKnowsPython
Country,,
United States of America,11095,6251
Germany,4947,2647
India,4231,2128
United Kingdom of Great Britain and Northern Ireland,3224,1638
Ukraine,2672,963
...,...,...
"Micronesia, Federated States of...",1,0
Nauru,1,0
Chad,1,1
Djibouti,1,0
Solomon Islands,1,0

In [67]:
python_df['PctKnowsPython'] = (python_df['NumKnowsPython']/python_df['NumRespondents']) * 100
python_df

,NumRespondents,NumKnowsPython,PctKnowsPython
Country,,,
United States of America,11095,6251,56.340694
Germany,4947,2647,53.507176
India,4231,2128,50.295438
United Kingdom of Great Britain and Northern Ireland,3224,1638,50.806452
Ukraine,2672,963,36.040419
...,...,...,...
"Micronesia, Federated States of...",1,0,0.000000
Nauru,1,0,0.000000
Chad,1,1,100.000000
Djibouti,1,0,0.000000
Solomon Islands,1,0,0.000000

In [68]:
python_df.sort_values(by='PctKnowsPython', ascending=False, inplace=True)

In [71]:
python_df.head(50)

,NumRespondents,NumKnowsPython,PctKnowsPython
Country,,,
Belize,2,2,100.000000
Brunei Darussalam,3,3,100.000000
Dominica,1,1,100.000000
Samoa,1,1,100.000000
Central African Republic,1,1,100.000000
Niger,1,1,100.000000
Chad,1,1,100.000000
Lesotho,1,1,100.000000
Saint Kitts and Nevis,1,1,100.000000
Mauritania,5,4,80.000000
"Congo, Republic of the...",8,6,75.000000
Libyan Arab Jamahiriya,4,3,75.000000
Liberia,4,3,75.000000
Guyana,3,2,66.666667
Democratic Republic of the Congo,3,2,66.666667
Monaco,3,2,66.666667
Bhutan,3,2,66.666667
North Korea,3,2,66.666667
Sierra Leone,3,2,66.666667
Zimbabwe,26,17,65.384615
El Salvador,19,12,63.157895
Kuwait,8,5,62.500000
Singapore,177,110,62.146893
Israel,604,360,59.602649
South Korea,146,87,59.589041
Rwanda,22,13,59.090909
Uganda,39,23,58.974359
Kenya,180,106,58.888889
Morocco,98,57,58.163265
Iceland,31,18,58.064516
Japan,288,167,57.986111
Chile,133,77,57.894737
China,406,233,57.389163
Tajikistan,7,4,57.142857
Sudan,7,4,57.142857
Mozambique,7,4,57.142857
United States of America,11095,6251,56.340694
France,2110,1187,56.255924
Maldives,16,9,56.250000
Yemen,18,10,55.555556
Luxembourg,40,22,55.000000
Turkmenistan,11,6,54.545455
Ireland,270,147,54.444444
Guatemala,41,22,53.658537
Finland,386,207,53.626943
Germany,4947,2647,53.507176
Sri Lanka,163,87,53.374233
Andorra,15,8,53.333333
Zambia,15,8,53.333333
Canada,2104,1120,53.231939

In [72]:
python_df.loc['Japan']

NumRespondents    288.000000
NumKnowsPython    167.000000
PctKnowsPython     57.986111
Name: Japan, dtype: float64